# Generated by Django 4.1.1 on 2022-09-22 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CadastroFilmes',
            new_name='CadastroFilme',
        ),
    ]
